apiVersion: v1
data:
  client-ca.crt: |
    {{ .Values.conf.certs.cacrt }}
  client.crt: |
    {{ .Values.conf.certs.clientcrt }}
  client.key: |
    {{ .Values.conf.certs.clientkey }}
kind: Secret
metadata:
  name: {{ .Values.conf.secretName }}
  namespace: {{ .Values.conf.namespace }}